Hello-microvers project
ClarenceAtim/Hello-microvers pull request #1
Opened 2023-04-25 17:33 UTC by ClarenceAtim

I created this project using:
-index.html
-style.css
-linters
-descriptive Readme file

2023-04-26 05:52 UTC, PinkMoon25 requested changes
Hi @ClarenceAtim , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media3.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif"/>

## Highlights
Linter setup :heavy_check_mark: 
github flow :heavy_check_mark: 
node modules ignored :heavy_check_mark: 
html and css file :heavy_check_mark: 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

**- [ ] [OPTIONAL] In future I would suggest to make sure our commit messages start with a capital letter, and also try to use the imperative tense like "Add markup and style" rather than "Added markup and style" just some best practices** 

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Describe your project in 1 or 2 sentences.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Describe the tech stack and include only the relevant sections that apply to your project.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Describe between 1-3 key features of the application.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Add a link to your deployed project.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Describe how a new developer could make use of your project.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +> Describe 1 - 3 features you will add to the project.
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on README.md
> +_NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setti
- [ ] good job so far, I would suggest that we remove this placeholder texts from our Readme to make it professional, these placeholder texts are present only to help us fill in the information, and we should avoid it in the final outcome, so please remove all these placeholder texts from your Readme :+1:

2023-04-26 05:52 UTC, PinkMoon25 commented on .gitignore
> +node_modules
- [ ] well done, however, please notice that as mentioned in the project requirements we have to create a text.md file with the text "This file should be ignored by git". and then add this file to the gitignore just like you have added the node_modules, this will ensure the file is ignored and will not be present in the repo :+1:

2023-04-26 07:02 UTC, usorfaitheloho requested changes
Hi @Zafron047  , 

>You are almost there!
Great effort so far, but unfortunately there are some issues that you need to review in order to get your project approved, but you got this!

![test](https://raw.githubusercontent.com/wickathou/client-assets/main/end-design/code-reviews/sorry.gif)
>

## Required Changes ♻️
- [ ] As suggested by the previous reviewer, please add a `test.md` file in the root directory of your project and add the `test.md` file in your `.gitignore` file, this is done to practice how `.gitignore` file can be used to ignore some files in our project 😄 
_Check the comments below to see technical issues found during this review._

## Optional suggestions
- [ ] It is a good practice to always remove commented lines of code when executing our final codebase to ensure a legible code free from error that doesn't consume unnecessary space. Kindly remove these lines of commented code and all others in your README file

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
<br/>

## Highlights
- Good work following HTML and CSS best practices :100: 
<br/>
<br/>
<br/>
Feel free to leave any questions or comments in the PR thread mentioning me so I can see the notification and reply `@faith eloho usor`.


Cheers and Happy coding!👏👏👏
<br/>
<br/>
<br/>
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-26 07:02 UTC, usorfaitheloho commented on README.md
> +-->
[Optional]

It is a good practice to always remove commented lines of code when executing our final codebase to ensure a legible code free from error that doesn't consume unnecessary space . Kindly remove this lines of commented code and all others in your README file😄

2023-04-26 08:06 UTC, ClarenceAtim commented on README.md
> +-->
@usorfaitheloho can you help me with a video to show me how to add the test.md file please because I did that but I don't understand how to do it please

2023-04-26 08:08 UTC, Nemwel-Boniface reviewed
## Hello @ClarenceAtim   👋,

I am Nemwel your reviewer.


## _This is an additional review as a result of the second opinion request._

I have received your second opinion request complaining about the review made by @PinkMoon25  . Kindly note the following:
1. When you request for a second opinion, you are not supposed to make any commits, request for another review in your dashboard, merge/ closs the PR until the second opinion request has been investigated and processed. Otherwise the outcome of the second opinion will have changed.

However since the requested mandatory changes by @usorfaitheloho  are already met, your project is ready for approval :rocket: . KIndly submit your project in your dashboard and your project will be immediately approved by the next reviewer. :slightly_smiling_face: 

**Note:** Kindly ensure that you remove the commented-out lines from your README before you resubmit your project for review in your dashboard.

In case anything is not 100% clear tag me @Nemwel-Boniface so that I get the notification.

Keep rocking 🚀!

2023-04-26 08:08 UTC, Nemwel-Boniface commented on README.md
> +<p align="right">(<a href="#readme-top">back to top</a>)</p>
- [ ] [OPTIONAL] - Even though this was not mentioned to you by any of the other reviewers, in future projects where you do not have a deployment of your project or you will deploy but not at the moment, it would be better to remove this section completely from your project README and only include it again once you make a deployment of your project.

2023-04-26 08:08 UTC, Nemwel-Boniface commented on README.md
> +-->
- [ ] Kindly ensure that you remove this commented-out code from your README before you submit for review. Otherwise the next reviewer might not approve your project.

2023-04-26 08:14 UTC, AbelG101 approved these changes
![](https://media.giphy.com/media/eKfovWZOlOpbTDEX9F/giphy.gif)

# Hi @ClarenceAtim 👋, 

**Your project is complete!  There is nothing else to say other than... it's time to merge it. 
Congratulations! 🎉 🥳🥇**

## Highlights
- Correct use of GitHub Flow ✔
-  Well-structured files ✔
- All linter checks are passing ✔
- Descriptive PR title with a good summary ✔

## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 08:22 UTC, AbelG101 reviewed
![](https://media.giphy.com/media/PkFYci8BUkmdA7K1qa/giphy.gif)

# Hi @ClarenceAtim 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- You have submitted a project, that isn't part of this milestone please make sure you submit the proper PR link as this milestone is the "Portfolio: setup and mobile first" & not the "Hello Microverse". 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-04-28 10:15 UTC, merged